### ISSUE TITLE
Auto-deploy new containers

### ISSUE THREAD

**Issue by hozn** [freezingsaddles/freezing-compose#2]
Containers are set to auto-build on Docker Hub.

Let's auto-deploy them too.  https://github.com/tuxity/docker-image-puller

**Comment by obscurerichard** [comment]
With the changes to Docker Hub requiring a paid Team subscription to build containers, containers are no longer building there. But we could resolve this in other ways, such as https://github.com/freezingsaddles/freezing-web/issues/114

**Comment by obscurerichard** [comment]
This is resolved by https://github.com/freezingsaddles/freezing-web/issues/114 and https://github.com/freezingsaddles/freezing-sync/pull/49 being fixed. We now use GitHub Actions for freezing-web and freezing-sync to publish container updates.  The next time we need to make an update to these packages we can just merge to the default branch.
